name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.100'

      - name: Restore dependencies
        run: dotnet restore ZatcaEGS/ZatcaEGS.csproj

      - name: Build the project
        run: dotnet build ZatcaEGS/ZatcaEGS.csproj --configuration Release

      - name: Publish the project
        run: dotnet publish ZatcaEGS/ZatcaEGS.csproj --configuration Release --output publish

      - name: Create zip artifact
        uses: actions/zip@v2
        with:
          name: ZatcaEGS.zip
          path: publish

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ZatcaEGS.zip
          path: ZatcaEGS.zip

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TITLE: "Release v${{ github.event.release.tag_name }}"
          RELEASE_BODY: "Release v${{ github.event.release.tag_name }}"
        with:
          tag-name: ${{ github.event.release.tag_name }}
          release-name: ${{ github.event.release.tag_name }}
          draft: false
          prerelease: false
